### ISSUE TITLE
Convert to vue-cli plugin

### ISSUE THREAD

**Issue by manico** [chmjs/chameleon-bundle#5]
To make it more flexible, we need to update this template to vue-cli plugin like we have other plugins.

**Comment by Lanchi** [comment]
This is done and new repo is created [vue-cli-plugin-chameleon-bundle](https://github.com/chmjs/vue-cli-plugin-chameleon-bundle) so this one can be deleted.

Vue CLI messed a few thing up for lib target in their latest release - they don't consider some `vue.config.js` options at all, namely:
- entry must be provided in command as an argument, otherwise `App.vue` is used
- name must be provided in command as an argument
- libraryTarget isn't considered, three builds (common, umd and umd.min) are always produced
- file name override in extract-css plugin is also overwritten by `vue-cli-service` internal logic

All of these problems are handled either by providing arguments inside `package.json` commands, either by `cleanup.js` script which gets called on `build-bundle` command. These steps should be implemented to our other bundles which use vue-cli, because as soon as we update their node_modules, build will break.

Basic documentation (usage and options) is added to README and to [Chameleon docs](https://chameleon-docs.nsoft.com/developers/bundles/vue-cli-plugin.html)
